### ISSUE TITLE
Tapping on create account button crashing the app 

### ISSUE THREAD

**Issue by iamirzashowvik** [dinurymomshad/listify#52]
I tried running the app on a real device. 
When I tap on "Create Account", the app got crashed.

**Comment by momshaddinury** [comment]
### Steps to reproduce:

1. Open the app
2. Logout if already logged in.
3. Click on **Create Account** button

_Current_: App crashes with a error screen
_Expected_: User should be able to create an account

Debug log:
```Performing hot restart...
Syncing files to device sdk gphone x86...
Restarted application in 1,967ms.
W/listify.listif(12001): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)

======== Exception caught by widgets library =======================================================
The following assertion was thrown building Consumer(dirty, dependencies: [UncontrolledProviderScope], state: _ConsumerState#73861):
ref.listen can only be used within the build method of a ConsumerWidget
'package:flutter_riverpod/src/consumer.dart':
Failed assertion: line 474 pos 7: 'debugDoingBuild'

The relevant error-causing widget was: 
  Consumer Consumer:file:///E:/Personal/listify/lib/views/screens/k_base_screen.dart:12:13
When the exception was thrown, this was the stack: 
#2      ConsumerStatefulElement.listen (package:flutter_riverpod/src/consumer.dart:474:7)
#3      _SignupScreenState.body (package:listify/views/screens/auth/sign_up_screen.dart:30:9)
#4      _BaseView.build.<anonymous closure>.<anonymous closure> (package:listify/views/screens/k_base_screen.dart:23:38)
#5      AsyncValueX.when.<anonymous closure> (package:riverpod/src/common.dart:264:24)
#6      AsyncData._map (package:riverpod/src/common.dart:161:16)
#7      AsyncValueX.when (package:riverpod/src/common.dart:263:12)
#8      _BaseView.build.<anonymous closure> (package:listify/views/screens/k_base_screen.dart:13:49)
#9      Consumer.build (package:flutter_riverpod/src/consumer.dart:269:20)
#10     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:371:19)
#11     StatefulElement.build (package:flutter/src/widgets/framework.dart:4870:27)
#12     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:431:20)
#13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4754:15)
#14     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#15     Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4735:5)
#17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4919:11)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
...     Normal element mounting (19 frames)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#38     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#39     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (263 frames)
#302    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#303    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#304    Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#305    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5845:32)
#306    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6445:17)
#307    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#308    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#309    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#310    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#311    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#312    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#313    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#314    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#315    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#316    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#317    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#318    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#319    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#320    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#321    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#322    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#323    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#324    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#325    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#326    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#327    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#328    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#329    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#330    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#331    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6291:14)
#332    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#333    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#334    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#335    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#336    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#337    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#338    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#339    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#340    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#341    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#342    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#343    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#344    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#345    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#349    _invoke (dart:ui/hooks.dart:151:10)
#350    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#351    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
====================================================================================================
```
